apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-volume
  namespace: healthcarex-demo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi